services:
  db:
    container_name: postgres
    image: postgres
    environment:
      TZ: 'GMT+2'
      PGTZ: 'GMT+2'
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: