spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/coupons
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
